### ISSUE TITLE
Layout: Drawer menu para usuário logado

### ISSUE THREAD

**Issue by AndreLaranjeira** [Hugo-NF/meau-app#39]
O drawerMenu para usuário logado é constante. Dessa forma, essa "página" deve ser criada.

Revisor: Luiz

**Comment by Hugo-NF** [comment]
Related links:

https://reactnavigation.org/docs/nesting-navigators
https://reactnative.dev/docs/dimensions
https://github.com/pedreviljoen/react-native-menu/issues/80
https://github.com/pedreviljoen/react-native-menu/blob/master/index.js
